### PR TITLE
Hide menu button only on the screens which supports hover effect.

### PR DESCRIPTION
**Pull request by yaroslavD2L**

### CODE REVIEW

**Comment by yaroslavD2L** [comment]
https://trello.com/c/zZ7iSHn4/658-folio-android-ios-tile-menu-item-doesnt-show-up-on-mobile-device

**Comment by yaroslavD2L** [comment]
@rcausey, can you take a look?

**Comment by yaroslavD2L** [comment]
image

**Comment by yaroslavD2L** [comment]
Menu is visible all the time on devised that doesn't support hover.

**Comment by jstefaniuk-d2l** [comment]
Just verify that if `showMenu` is false the button doesn't appear, and that all of the old "show button" cases still work on non-mobile screens (adding the media query could possibly make the `opacity: 0` more-specific than the other `opacity: 1` cases and override them)

If there _are_ issues, I'd do "If _not_ hover - opacity: 1"

**Comment by yaroslavD2L** [comment]
I thought about your case also ("If not hover - opacity: 1"). It's better to show menu button all the time instead of hiding it, in a case when media query does not work somehow. 
That is how it looks with `hide-menu = true` on non-mobile and mobile screens. 
image

**Comment by rcausey** [comment]
Not sure what you mean with the last screenshot. We'd have to go through designers to do something like that. I think showing the button all the time for mobile devices is fine.

**Comment by jstefaniuk-d2l** [comment]
The second half of my post was a bit unclear

Are you able to tab to the button on desktop, and navigate the menu with the keyboard, with everything showing up as appropriate? (I just want to make sure none of the `opacity: 1` setting css is overwritten by the new media query)

If so I'll merge

**Comment by yaroslavD2L** [comment]
@jstefaniuk-d2l, I just checked on the desktop and keyword navigation works well.

**Pull request merged**
